[phases.setup]
nixPkgs = ['python311', 'nodejs_20', 'npm']

[phases.install]
cmds = [
    'cd dashboard && npm install',
    'pip3 install -r requirements.txt',
    'cd tiktok_uploader/tiktok-signature && npm install'
]

[phases.build]
cmds = ['cd dashboard && npm run build']

[start]
cmd = 'bash start.sh'
